server:
  port: 9995
  context-path: /cmfz
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cmfz?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 123123
  http:
    encoding:
      charset: UTF-8
      force: true
  freemarker:
      charset: UTF-8
mybatis:
  mapper-locations: com/baizhi/mapper/*.xml

  #jsp热部署
  jsp-servlet:
     init-parameters:
     development: true

fdfs:
  soTimeout: 30
  connectTimeout: 60
  thumbImage: #缩略图生成参数
    width: 150
    height: 150
  trackerList: #TrackerList参数,支持多个
    - 192.168.11.129:22122
  pool:
     max-total: 100
     max-wait-millis: 60